### ISSUE TITLE
IList map to return IList rather than Iterable

### ISSUE THREAD

**Issue by venkatd** [marcglasberg/fast_immutable_collections#10]
Thanks for this library, it is helping improve state management for some of our more complex widgets.

What is the reasoning that an `IList<T>.map` returns an `Iterable<T>` rather than the more specific `IList<T>`? If we return another `IList` we can chain it with other methods and pass it around. I find myself having to explicitly call `.toIList()` every time anyway.

**Comment by psygo** [comment]
As far as I remember, that choice was based on [`List.map` returning an `Iterable`][list.map], it matches their APIs/impedances.


[list.map]: https://api.dart.dev/stable/2.12.2/dart-core/Iterable/map.html

**Comment by venkatd** [comment]
Ok thanks for the explanation.

Didn't consider the laziness. I suppose you want `IList.map` to be lazy just like `List.map` and if you return an `IList` it would be forced to evaluate everything.
