### ISSUE TITLE
Predicate

### ISSUE THREAD

**Issue by Solido** [marcglasberg/fast_immutable_collections#18]
Would you accept a PR with 
`typedef Predicate<T> = bool Function(T element);`

Replacing any form
`T? firstWhereOrNull(bool Function(T) test)`

with 
`T? firstWhereOrNull(Predicate<T> test)`

Just for readability purposes. 
Need to check but there should be no performances penalties.

Thx for the feedback

**Comment by marcglasberg** [comment]
I would.
