### ISSUE TITLE
Dart-FP integration

### ISSUE THREAD

**Issue by Solido** [marcglasberg/fast_immutable_collections#22]
Dart-FP => dfp

Open discussion for planning

For the first step can we consider a breaking change in FIC and plan a for 6.0 release ?

Is there some entites than we can remove from _fic_ and depends directly on _dfp_ ?
Maybe evolve _dfp_ entities for some new requirements too ?

@SandroMaglione

**Comment by SandroMaglione** [comment]
[As we discussed](https://github.com/marcglasberg/fast_immutable_collections/pull/20), we could implement some extension methods that add functional programming to FIC. The extension would not be included in FIC core but you would need to explicitly import it.
Functional types will come from [fpdart](https://github.com/SandroMaglione/fpdart).

@marcglasberg what do you think about this idea? How do you propose we go about a possible integration and implementation?

**Comment by SandroMaglione** [comment]
While working on the extension for [List](https://github.com/SandroMaglione/fpdart/blob/main/lib/src/list_extension.dart) and [Map](https://github.com/SandroMaglione/fpdart/blob/main/lib/src/map_extension.dart) on fpdart, I realised that these extension can be used also for `IList` and `IMap` as they are, without modifications. The only concern remained is performance. Nonetheless, fpdart using those extension already offers some quite handy methods to work with fp on dart collections.

@Solido @marcglasberg  How would you suggest to move from here? Is there a way to involve FIC to improve performances?

**Comment by marcglasberg** [comment]
@SandroMaglione Hello, I am very sorry for the delay. I've been working 12 hours per day and haven't had much free time.

I don't have experience with fp, and don't know exactly what you are trying to achieve. When you say: 

> As we discussed, we could implement some extension methods that add functional programming to FIC. The extension would not be included in FIC core but you would need to explicitly import it.

Why exactly would FIC need to import extension methods? The users who are interested in fp can import both FIC and your lib, and they would have the extension methods working. I could also add to the docs a link to your lib explaining that they should import both if they want the fp features.

**Comment by SandroMaglione** [comment]
> The users who are interested in fp can import both FIC and your lib, and they would have the extension methods working.

Yes, that is what I realised while working on the extensions. You can use the methods from fpdart (`bind`, `ap`, `head`, etc.) also on `IList` since the extension is on `Iterable`.
My last concern at this point is performance. I wonder if there could be a way to have better performances if the extension is directly on `IList` (not sure about that, maybe you can tell me about this).

> I could also add to the docs a link to your lib explaining that they should import both if they want the fp features.

I would be willing to make a PR for this.

**Comment by marcglasberg** [comment]
No, if the extension is in the FIC package, or if it's in the `IList` itself, it won't make any performance difference. And it also won't make any usability difference, since the syntax the user needs to write to use it is the same.

**Comment by marcglasberg** [comment]
@SandroMaglione One detail: The `IList` and `ISet` are `Iterable`s. However, the IMap is not an `Iterable`, and it's also not a `Map`.

**Comment by SandroMaglione** [comment]
Okay. I believe then that by using the `fpdart` extensions it is now possible to use FIC and FP together by importing both packages separately. 

> However, the IMap is not an Iterable, and it's also not a Map.

This could be an issue. Do you have an idea on how this can be fixed? The only solution I can think of is to create a specific extension for `IMap`, which would break the separation between FP and FIC. Any other idea?

**Comment by marcglasberg** [comment]
I don't see a way for you to create an extension for the IMap without importing the IMap.
