### ISSUE TITLE
JSON Serialization of IMap Keys

### ISSUE THREAD

**Issue by TimWhiting** [marcglasberg/fast_immutable_collections#26]
Because this uses toJsonK and fromJsonK, non-String keys don't automatically get converted to Strings in the toJson map output, and also don't get converted back from Strings in fromJson. 

PR #25 is a temporary solution until json_serializable can detect and handle these cases.

Here is the json_serializable issue
https://github.com/google/json_serializable.dart/issues/396

**Comment by marcglasberg** [comment]
Fixed in version **7.0.6-dev0**

Thanks for the PR!
