### ISSUE TITLE
using lock as getter is an antipattern

### ISSUE THREAD

**Issue by jinyus** [marcglasberg/fast_immutable_collections#3]
Hello, I love this package but the lock extension is a misuse of getters. lock should be an alias of toIList() since it transforms the original list rather than return data related to it. Please consider deprecating the lock getter and replace it with a lock() method.

**Comment by marcglasberg** [comment]
You are right, of course. I am abusing getters. This is for those that like the use the tersest possible way, even if it bends the rules a bit. However, you are not forced to use it. Please just ignore it and use the `toIList()` method. I have provided both ways for this reason.
