### ISSUE TITLE
Remove `////...` comments

### ISSUE THREAD

**Issue by purplenoodlesoop** [marcglasberg/fast_immutable_collections#30]
Hello! 

First of all, thank you for this excellent package. It is a total lifesaver.

There is a small issue with the documentation that can be easily removed. 5 classes have section dividers in their visible documentation. Because the `dartdoc` treats everything that goes after three slashes as a doc comment, dividers consisting of slashes end up in the visible documentation

The affected classes are: `IList`, `IMap`, `IMapImpl`, `IMapOfSets`, `IMapOfSetsConst`.

I will be more than happy to submit a PR :)

**Comment by marcglasberg** [comment]
I'm glad you like the package.

Yes, I like these dividers, but they must have a space so that they don't end up in the documentation. Like so:

```
\\ \\\\\\\\\\\\\\\\\\\\\\\\\\\\
```

Hopefully, I have fixed this for version [7.1.2].

Please let me know if you still see this problem. Thanks!
