### ISSUE TITLE
Undocumented classes

### ISSUE THREAD

**Issue by purplenoodlesoop** [marcglasberg/fast_immutable_collections#31]
Hello!

There are three classes which purposes are not very clear.

Why are the classes `L`, `M` and `S` are publically exposed and what do they do?

**Comment by marcglasberg** [comment]
Please see version [7.1.1-dev0]. Does it fix the problem for you?

These are important internal classes. Dart visibility is very problematic, and I had two alternatives. First was putting all classes into the same file. This would result in a file with many thousands of lines.

The other alternative was using some tricks that would make parts of the code harder to understand. This is actually what I ended up doing. You can check the latest commit if you are curious.

**Comment by marcglasberg** [comment]
Please see version [7.1.1].
