### ISSUE TITLE
Possibly incorrectly exposed classes

### ISSUE THREAD

**Issue by purplenoodlesoop** [marcglasberg/fast_immutable_collections#32]
Hello!

There seem to be some classes that should not be exposed. 

Can class `InternalsForTestingPurposesIList`, `InternalsForTestingPurposesIMap` and `InternalsForTestingPurposesISet` be kept private to not pollute the scope of entities that the package exposes?

I will be more than happy to submit a PR :)

**Comment by marcglasberg** [comment]
Please see version [7.1.1].
