### ISSUE TITLE
deepEquals compare objects using [identical] 😓

### ISSUE THREAD

**Issue by yehorh** [marcglasberg/fast_immutable_collections#36]
The extension method `deepEquals` compare objects using the `identical` instead  the `==` operator.

https://github.com/marcglasberg/fast_immutable_collections/blob/934e2a336a60ec881cd67acd0d987e472c7c1ff9/lib/src/base/iterable_extension.dart#L115-L117

**Comment by marcglasberg** [comment]
Now.
