### ISSUE TITLE
`averageBy`'s documentation code is that of `sumBy`

### ISSUE THREAD

**Issue by narumincho** [marcglasberg/fast_immutable_collections#44]
https://pub.dev/documentation/fast_immutable_collections/latest/fast_immutable_collections/FicIterableExtension/averageBy.html

<img width="938" alt="image" src="https://user-images.githubusercontent.com/16481886/190560175-dd71db4c-12a3-4ea0-b8cd-c2cb77b8e649.png">

**Comment by marcglasberg** [comment]
Fixed. Thank you!
