### ISSUE TITLE
Use unsafe immutable collections for JSON parsing

### ISSUE THREAD

**Issue by Reprevise** [marcglasberg/fast_immutable_collections#54]
When creating collections from JSON, the package is creating copies of the original collections when it doesn't have to.

For example, the `IMap.fromJson` constructor code:

```dart
factory IMap.fromJson(
  Map<String, Object?> json,
  K Function(Object?) fromJsonK,
  V Function(Object?) fromJsonV,
) =>
    json
        .map<K, V>(
            (key, value) => MapEntry(fromJsonK(_safeKeyFromJson<K>(key)), fromJsonV(value)))
        .lock;
```

Considering the fact that a _new_ map is being created via `.map`, wouldn't it be safe to use `.lockUnsafe` here? (And in the other constructors `IList` and `ISet` as well.)

**Comment by marcglasberg** [comment]
Absolutely. Good catch! I will fix this.

**Comment by marcglasberg** [comment]
Done. Note just the IMap had this problem. IList and ISet where created differently. Thank you.

**Comment by Reprevise** [comment]
@marcglasberg Can you explain why IList and ISet don't have this issue?

Both `IList.fromJson` and `ISet.fromJson` use their default constructors to create their respective collections which AFAIK _does_ create copies unlike `ISet.unsafe` and `IList.unsafe`.

**Comment by marcglasberg** [comment]
`IMap` is creating a map first, and then locking it. 

But `IList` and `ISet` are not. For those you have an `Iterable`, and then you lock it directly. The Iterable is lazy, it will be used internally when creating the IList/ISet. No intermediary mutable `List` or `Set`s are created in this case.
