### ISSUE TITLE
Const constructors?

### ISSUE THREAD

**Issue by giaur500** [marcglasberg/fast_immutable_collections#56]
I have immutable class with const constructor and all fields final. I don't want to make them nullable or required. Instead, I want to set default value in const constructor. With regular list, I can do that this way (`myList` field must be final):

```
const MyClass({
this.myList = const [],
});
```
But I can't do the same with your immutable list, because there's no const constructor. Is there any workaround for that? From some reasons, I don't want to make `myList` field nullable and also I don't want it to be required, I want to assign default value instead.

**Comment by marcglasberg** [comment]
There is a const constructor:

```
const IList<int> ilist1 = IListConst([1, 2, 3]);
const IList<int> ilist2 = IListConst([]);
const IList<int> ilist3 = IListConst([1, 2], ConfigList(isDeepEquals: false));
```

That's item 2.1 of the documentation.
