### ISSUE TITLE
Suggestion: Use `@useResult` instead of `@useCopy` (or use both)

### ISSUE THREAD

**Issue by bvoq** [marcglasberg/fast_immutable_collections#61]
Consider the following example.
```
@immutable
class MessageThread {
  const MessageThread(this._messages);
  final IList<String> _messages;
  IList<String> get messages => _messages;
}

void main() {
  String aStringWithDots = "a.b.c";
  final bla = MessageThread(["a", "b", aStringWithDots].lock);
  debugPrint("This is a message thread: ${bla.messages}");
  bla.messages.add("d");
  debugPrint("This is a message thread: ${bla.messages}");
}
```

This is of course incorrect usage and the string d won't ever be added to the immutable list (it would be if you replaced IList with List).

However, if you would add the `@useResult` annotation to the add function it would look like this:
```
  /// Return a new list with [item] added to the end of the current list,
  /// (thus extending the [length] by one).
  @useCopy
  @useResult
  IList<T> add(T item) {
    final result = IList<T>._unsafe(_l.add(item), config: config);
```

and in the IDE you get a type notification for this:
<img width="1311" alt="image" src="https://github.com/marcglasberg/fast_immutable_collections/assets/3169217/b226e0fb-abc2-4a83-9499-0f117b730c3a">

**Comment by marcglasberg** [comment]
The only reason I did not use `@useResult` to start with is that, at the time, the Flutter IDE plugin had a bug and was issuing weird warnings when using that annotation. At the time, I opened an issue, and they said they would fix it soon. Meanwhile I created this `@useCopy` annotation as a temporary placeholder.

Thanks for noticing this. I just published version **9.2.0**.
