### ISSUE TITLE
IHashMap Implementation

### ISSUE THREAD

**Issue by point-source** [marcglasberg/fast_immutable_collections#62]
I am looking for an immutable version of Dart's HashMap (not the LinkedHashMap). Is there a reason why this package doesn't provide that? Can I reasonably assume that a HashMap variant would be more memory efficient than the current IMap based on a LinkedHashMap or is that not really the case?

**Comment by marcglasberg** [comment]
Got you covered.

`IMap` uses a `ListMap` internally:

```
MFlat(Map<K, V> _map, {ConfigMap? config})
      : _map = ListMap.of(_map, sort: (config ?? IMap.defaultConfig).sort);
```

And the `ListMap` uses a `HashMap` internally:

```
ListMap.of(
    Map<K, V> map, {
    bool sort = false,
    int Function(K a, K b)? compare,
  })  : assert(compare == null || sort == true),
        _map = HashMap.from(map),
 ...
```

**Comment by point-source** [comment]
Oh lol, thanks! I seem to have misread the code then. I thought the IMap employed Map which defaults to LinkedHashMap. Thanks for clarifying and thanks for providing this package. I use it in nearly every project I work on and it's been fantastic.

**Comment by marcglasberg** [comment]
Glad you like it! :)
