### ISSUE TITLE
IList `replaceFirstWhere` unnecessary nullable

### ISSUE THREAD

**Issue by TekExplorer** [marcglasberg/fast_immutable_collections#64]
from `IList`:
```dart
  @useCopy
  IList<T> replaceFirstWhere(
    bool Function(T item) test,
    T Function(T? item) replacement, { // here
    bool addIfNotFound = false,
  }) {
    final int index = indexWhere(test);
    return (index != -1)
        ? put(index, replacement(this[index])) // and here
        : addIfNotFound
            ? add(replacement(null))
            : this;
  }
```
there's no reason for `replacement` to have item as `T?` as we already guarantee the item exists, don't we?

**Comment by TekExplorer** [comment]
Hm. i think i see, if `addIfNotFound` is true, then null is passed in
this seems like a bad api to me

**Comment by marcglasberg** [comment]
Yes, not a perfect API. But also, an `orElse` would only be used if `addIfNotFound` is true. Which is also not a good API (having a useless parameter depending of another parameter being true or false).

The only real solution would be to have two different methods.

In any case, any of these would be breaking changes, and I don't think they are worth it. Things as they are, I'd recommend you throw an error when you are not using that parameter, in the first line of your replacement function. This will let you treat that parameter as non-nullable after this line:

T replacement (T? item) { 
   if (item == null) throw AssertionError();
   ...
}

**Comment by TekExplorer** [comment]
> Yes, not a perfect API. But also, an `orElse` would only be used if `addIfNotFound` is true. Which is also not a good API (having a useless parameter depending of another parameter being true or false).

...no? the very existence of an `orElse` implies it, the boolean would be unecessary - but anyway, i guess i'll just use an extension if i need to. throwing or using null checks feels awful when it's not necessary - i like my type and null safety.

**Comment by marcglasberg** [comment]
Sure, you can even add two extensions methods. Maybe call them `replaceFirstOrDiscard` and `replaceFirstOrAdd` or something similar.
