### ISSUE TITLE
Best Practices for Mutating Collections Multiple Times

### ISSUE THREAD

**Issue by shtse8** [marcglasberg/fast_immutable_collections#65]
I am working with the fast_immutable_collections package in Dart and have a question regarding the optimal way to handle multiple mutations on a collection. My goal is to understand the best practices for performance, especially in relation to the copy-on-write optimization that this package offers.

Here's the core of my query: When needing to mutate a collection multiple times, is it more efficient to unlock the collection, perform all mutations, and then lock it again, or should I simply use the immutable collection methods for each addition?

To give a concrete example, I am comparing these two approaches:

Approach 1: Unlocking and Locking

```dart
var nums = IList();
final newNums = nums.unlock;
for (var i = 0; i < 10; i++) {
  newNums.add(i);
}
nums = newNums.lock;
```

Approach 2: Using Immutable Collections

```dart
var nums = IList();
for (var i = 0; i < 10; i++) {
  nums = nums.add(i);
}
```

My concern is about the performance implications of these two methods, particularly regarding the copy-on-write feature. Does the first approach of unlocking and locking impact the optimization adversely? Or is it more efficient compared to adding items individually using immutable collection methods?

Any insights or recommendations on this would be greatly appreciated.

Thank you for your time and for maintaining this valuable package.

**Comment by marcglasberg** [comment]
You should simply use the immutable collection methods for each addition. 

It actually doesn't copy-on-write. Instead, it uses a special data structure that records only the change. And it will also detect internally that there were to many additions, and it will "flush" the contents from time to time, to optimize reading and memory.

In other words, I suggest you do what's easier for you, and trust FIC to do the necessary optimizations internally to be fast and save memory.

Of course, if you have a very large number of operations, you can always measure things yourself too see if it's fast. But FIC will have a very good performance most of the time.
