### ISSUE TITLE
Docs error?

### ISSUE THREAD

**Issue by busslina** [marcglasberg/fast_immutable_collections#80]
[Here](https://pub.dev/documentation/fast_immutable_collections/latest/fast_immutable_collections/ListMap-class.html), seems some lines missing:

![imagen](https://github.com/marcglasberg/fast_immutable_collections/assets/73592852/0db69d36-1564-4da0-8aae-45b438fdefbe)

**Comment by marcglasberg** [comment]
If you click the link, you'll see the complete documentation:

https://pub.dev/documentation/fast_immutable_collections/latest/fast_immutable_collections/ListMap/ListMap.unsafeFrom.html

It seems to be that previous screen only shows the first paragraph. I didn't create the documentation with this in mind, so I'd suggest you always click the link.

**Comment by busslina** [comment]
My bad hehe :)
