### ISSUE TITLE
Growable ListMap, with `insert` method.

### ISSUE THREAD

**Issue by busslina** [marcglasberg/fast_immutable_collections#81]
[Here](https://pub.dev/documentation/fast_immutable_collections/latest/fast_immutable_collections/ListMap/remove.html) it says that can return null but the return value is declared as `V` instead `V?`.

Then I see this:
```dart
@override
V remove(Object? key) {
  throw UnsupportedError("Can't remove from a ListMap.");
}
```

I came to `ListMap` looking for a structure similar to `LinkedHashMap`, which is inserted ordered, but which allows to insert a new element on first position. Can you suggest a best choice for this?

**Comment by marcglasberg** [comment]
Thanks, just fixed this to `V?`.

---

A `ListMap` is currently fixed-size, so it's not what you want. But it could be. I just implemented what I needed for my immutable structures (it's used in the `IMap` implementation), and did not think about all the potential features a `ListMap` could have.

First, all `ListMap` constructors would need to get a `growable` parameter, defaulting to `false`.

Then I'd suggest you could implement an `insert(index, key, value)` method, that only works when the `ListMap` growable, and would add a value into the `_map`, and then insert the value into the `_list` at the correct position.

If you want to implement it I'd accept a PR, as long as you also implement all the necessary unit tests into `list_map_test.dart`.

Check the current code in GitHub. I added this method:

```dart
  /// Inserts [key]/[value] at position [index].
  ///
  /// If the [key] already exists, the previous one will first be removed.
  ///
  /// Then, it will shift all objects at or after the index towards the end of the list,
  /// and add it at the given position.
  ///
  /// This only works if the `ListMap` is growable.
  /// The [index] value must be non-negative and no greater than [length].
  ///
  void insert(int index, K key, V value) {
    // TODO: Implement
    throw UnsupportedError("This is not yet supported, but will be in the future.");
  }
```

**Comment by busslina** [comment]
Okay, I will implement it soon

**Comment by busslina** [comment]
I'm sorry, I really hate testing. In this case wouldn't be very difficult but I ended creating my `PoweredLinkedHashMap`. For now it has just one method. I share it here and feel free to use it without any credit. If you want I can post here future updates on it (as I have it in a private repo).

### PoweredLinkedHashMap
```dart
import 'dart:collection';

class PoweredLinkedHashMap<K, V> implements Map<K, V> {
  PoweredLinkedHashMap();

  /// https://api.dart.dev/stable/3.4.3/dart-collection/LinkedHashMap-class.html
  ///
  /// A non-constant map literal, like {"a": 42, "b": 7}, is a LinkedHashMap.
  var _map = <K, V>{};

  @override
  V? operator [](Object? key) => _map[key];

  @override
  void operator []=(K key, V value) => _map[key] = value;

  @override
  void addAll(Map<K, V> other) => _map.addAll(other);

  @override
  void addEntries(Iterable<MapEntry<K, V>> newEntries) =>
      _map.addEntries(newEntries);

  @override
  Map<RK, RV> cast<RK, RV>() => _map.cast<RK, RV>();

  @override
  void clear() => _map.clear();

  @override
  bool containsKey(Object? key) => _map.containsKey(key);

  @override
  bool containsValue(Object? value) => _map.containsValue(value);

  @override
  Iterable<MapEntry<K, V>> get entries => _map.entries;

  @override
  void forEach(void Function(K key, V value) action) => _map.forEach(action);

  @override
  bool get isEmpty => _map.isEmpty;

  @override
  bool get isNotEmpty => _map.isNotEmpty;

  @override
  Iterable<K> get keys => _map.keys;

  @override
  int get length => _map.length;

  @override
  Map<K2, V2> map<K2, V2>(MapEntry<K2, V2> Function(K key, V value) convert) =>
      _map.map(convert);

  @override
  V putIfAbsent(K key, V Function() ifAbsent) =>
      _map.putIfAbsent(key, ifAbsent);

  @override
  V? remove(Object? key) => _map.remove(key);

  @override
  void removeWhere(bool Function(K key, V value) test) =>
      _map.removeWhere(test);

  @override
  V update(K key, V Function(V value) update, {V Function()? ifAbsent}) =>
      _map.update(key, update, ifAbsent: ifAbsent);

  @override
  void updateAll(V Function(K key, V value) update) => _map.updateAll(update);

  @override
  Iterable<V> get values => _map.values;

  String _msg(String message) => 'PoweredLinkedHashMap<$K, $V> -- $message';

  void insertAt(int index, K key, V value) {
    if (index < 0 || index > _map.length) {
      throw (_msg(
          'insertAt() -- Bad index -- Index: $index, Length: ${_map.length}'));
    }
    final entries = _map.entries.toList();
    _map = LinkedHashMap.fromEntries([
      ...entries.sublist(0, index),
      MapEntry(key, value),
      ...entries.sublist(index, entries.length),
    ]);
  }

  @override
  String toString() => _map.toString();
}

```

**Comment by marcglasberg** [comment]
Sure. `ListMap` has some nice properties regarding performance that you don't have in your implementation. You are recreating the map, so that's going to be slow for large maps. However, for most small maps it won't make a difference. I'm happy you solved your problem.

**Comment by busslina** [comment]
Thanks, I'm noting that and mark for study those performance techniques for when a have more time. :)
