### ISSUE TITLE
Major version for a Sponsor ?

### ISSUE THREAD

**Issue by ndelanou** [marcglasberg/fast_immutable_collections#83]
Changing the major version of the package just for adding a sponsor feels a bit odd.
Not judging for the sponsor, we all need to bring money on the table. I'm glad it helps/motivate you to maintain this useful package.

Also, looking at the repository history, there have been changes made on other files since the last version. That would have be nice to mention it in the Changelog:
* [02bf90b793d30cb07dabace06842cdb0ad8574f0](https://github.com/marcglasberg/fast_immutable_collections/commit/02bf90b793d30cb07dabace06842cdb0ad8574f0)
* [de84b765914d4199fd51e246fc6e61bbf036efe5](https://github.com/marcglasberg/fast_immutable_collections/commit/de84b765914d4199fd51e246fc6e61bbf036efe5)

**Comment by marcglasberg** [comment]
You are right, of course. My dumb excuse is that I have 16 packages to maintain, plus one documentation website, and 2 IntelliJ plugins, and I may not be paying enough attention to the versioning as I should.
